Add delayed extra package of dask
I'm getting AttributeError: 'dask' has no attribute 'delayed'. I guess that's because
`pip install dask` only installs the core dask packages which do not include the delayed API. `pip install dask[delayed]` fixed it.